### ISSUE TITLE
关于反混淆错误

### ISSUE THREAD

**Issue by atyvcn** [echo094/decode-js#1]
在使用sojson 反混淆这个脚本时https://jsd.cdn.zzko.cn/gh/atyvcn/jd_scripts@main/jx_one2shopping.js
会报Env is not defined 把 Env函数移动到反混淆脚本前面运行无报错但也无输出。
![image](https://user-images.githubusercontent.com/28555862/221418543-1a2afbbc-6419-469d-af40-152608c728a0.png)

在使用sojsonv7反混淆https://jsd.cdn.zzko.cn/gh/atyvcn/jd_scripts@main/jd_ty_help.js
![11](https://user-images.githubusercontent.com/28555862/221419414-2a9838cb-1b36-4c1f-ab53-0aa2ef2c2d28.png)

以及使用obfuscator 反混淆 https://jsd.cdn.zzko.cn/gh/leafTheFish/DeathNote@main/meituan.js
会报错部分错误加try { 可以继续输出。
![222](https://user-images.githubusercontent.com/28555862/221419432-4b9b59c1-390a-45af-88ee-1d2a2acc890e.png)

**Comment by echo094** [comment]
已针对上述3个脚本进行修复。

在反混淆时需要先将无关语句删除，保证混淆代码前面不存在其它代码，否则部分插件无法正常识别语句。

如有别的问题，可以提新的issue。
