### ISSUE TITLE
jsjiami vip可以解不

### ISSUE THREAD

**Issue by yangtuyun** [echo094/decode-js#10]
大佬，感谢你提供的工具，我尝试了jsjiami vip 的解混淆失败了，是现在还不能解付费的吗

**Comment by yangtuyun** [comment]
这是代码
https://playcode.io/1521035
感谢大佬

**Comment by echo094** [comment]
> 这是代码 https://playcode.io/1521035 感谢大佬

这个有关[llqplayer](https://www.llqplayer.com/)的混淆脚本有两项混淆内容：

1. eval上方的内容，这个是播放器核心代码
2. eval包括的内容，这个是userAgent校验代码，这部分有两个流程：
    1. 调用eval中的函数得到混淆后的代码字符串
    2. 调用eval执行混淆后的代码字符串

这两个代码块都是sojson类型的混淆，现已更新，你可以拆分成两部分分别解混淆，然后拼接。

更新后的插件可以提取eval中的语句，不需要去掉eval。

**Comment by yangtuyun** [comment]
感谢大佬，更新真积极，非常感谢
