### ISSUE TITLE
sojsonv7: 未知变种 寻求来源后适配

### ISSUE THREAD

**Issue by woshicaca** [echo094/decode-js#100]
[v7.txt](https://github.com/user-attachments/files/15855992/v7.txt)
这个v7也会报错，麻烦研究一下

**Comment by echo094** [comment]
去看了下公开的工具，混淆逻辑和之前相比没有变化。

这个样本可能是用户额外进行了一系列后处理，在全局范围观察到下述变化：

* RotateFunction的实现原理不变，但是函数结构有很大的变化
* stringArray相关的变量名被简化，使其可能与子作用域中的变量重名

后处理方法之复杂，给人一种这是V7内部测试版的感觉。

目前的方案是先完善stringArray的处理逻辑，但是对于公开版中不存在的后处理暂时不会在主线中进行适配。

**Comment by echo094** [comment]
链接 #96 具有同样的forStatement代替whileStatement特征

**Comment by huanzhiyi** [comment]
> 链接 #96 具有同样的forStatement代替whileStatement特征

https://note.ms/wfsx   这个样本不知道是不是同种类型的

**Comment by huanzhiyi** [comment]
> > https://note.ms/wfsx 这个样本不知道是不是同种类型的
> 
> 不是，这个样本只是把第一行version往后移了，把它移回第一行就行了
> 
> ```js
> var version_ = "LLQPlayer.Pro";
> ```
> 
> 还原后的代码还有一些其它的控制流转换操作，比如：
> 
> ```js
> function gen(len, step) {
>   var table = [];
>   for (var i = 0; i < len; i++) {
>     table[(i + step) % len] = [];
>   }
>   for (var i = 0; i < len; i++) {
>     for (var j = len - 1; j >= 0; j--) {
>       table[i][(j + step * i) % len] = table[j];
>     }
>   }
>   return table;
> }
> ```
> 
> 会生成一个二维矩阵，每个格子都指向某一行，将行作为switch语句的key

好的 感谢提醒，以为是同一类型。
