### ISSUE TITLE
解密后 v7有混淆

### ISSUE THREAD

**Issue by srlihg66** [echo094/decode-js#102]
其他遇见
https://paste.srlihg.link/TSnt
官网例子
https://www.jsjiami.com/
解密结果
https://paste.srlihg.link/X6X3
发现混淆还原不了 很多ob也有
有什么方法可以快速搞混淆吗？麻烦指点一下

**Comment by echo094** [comment]
你指的是哪种类型的混淆还原不了，如果是变量名，那确实不行，这是不可逆的。

**Comment by srlihg66** [comment]
> 你指的是哪一个标志性的还原，如果是标志性的，那确实不行，这是不可逆的。

好吧 就是他们设置的 a b什么的 变量名称
