### ISSUE TITLE
sojsonv7: TypeError: _0x379d66[_0x142c2e] is not a function

### ISSUE THREAD

**Issue by Eykszc** [echo094/decode-js#103]
[sojsonv7.zip](https://github.com/user-attachments/files/16266664/sojsonv7.zip)
类型: sojsonv7
输入: input.js
输出: output.js
处理全局加密...
Version var: _0xodu
Main call wrapper name: _0x6996
/workspaces/decode-js/src/plugin/sojsonv7.js:15
  return globalContext.evalSync(String(jsStr))
                       ^

TypeError: _0x379d66[_0x142c2e] is not a function
    at <isolated-vm>:1:6891
    at <isolated-vm>:1:5841
    at <isolated-vm>:1:6692
    at <isolated-vm>:1:7057
    at (<isolated-vm boundary>)
    at virtualGlobalEval (/workspaces/decode-js/src/plugin/sojsonv7.js:15:24)
    at decodeGlobal (/workspaces/decode-js/src/plugin/sojsonv7.js:258:3)
    at module.exports (/workspaces/decode-js/src/plugin/sojsonv7.js:767:9)
    at /workspaces/decode-js/src/main.js:36:10

Node.js v20.15.1

**Comment by echo094** [comment]
这是代码本身的问题（本身就没法运行，你可能拿到了二手代码）：

<img width="1000" alt="image" src="https://github.com/user-attachments/assets/a9d63f4a-7d55-4903-b25a-8e09c1e27c45">

图里的几个字符应该是`\x__`但是被改成了`\\x__`。

例如`\x73`本来是`s`，但是变成`\\x73`后就不再是`s`了，这就导致本来要调用的`split`函数变成了不存在的函数。

你修复一下这段代码就行。
