### ISSUE TITLE
obfuscator解密问题

### ISSUE THREAD

**Issue by Fast12138** [echo094/decode-js#109]
解密之后大量运算符，还有很多解密完全。比如
var O = m.rZJQc(X, I, !(-7562 + -1200 + 8762));
        V && (O += V);
        V = m.zjMQJ(m.ayFGU(m.akBpU(m.XFiVS(m.pYEEG(L.sig(O), "|"), m.OdXWQ(r)), "|"), new Date().getTime()), "|1");
        O = F.ua(V, !(-7271 + 1348 + 5923));

下面是用其他工具解密上面的的结果
        var O = X(I, true);
        V && (O += V);
        V = L.sig(O) + "|" + r() + "|" + new Date().getTime() + "|1";
        O = F.ua(V, true);
请问是我操作问题还是其他问题

**Comment by echo094** [comment]
你这个代码也没有完整版，从片段看是收集的局部语句没有还原完整，就这几行没法定位。

**Comment by Fast12138** [comment]
https://github.com/Fast12138/Auto-JavaScript-Action/blob/main/w.js
脚本送上

**Comment by echo094** [comment]
> https://github.com/Fast12138/Auto-JavaScript-Action/blob/main/w.js 脚本送上

你这是私有仓吧

**Comment by echo094** [comment]
常量表达式计算已经更新了。

局部语句方面我看不到你的样本，我这边也构造不出来你那种情况。如果这个问题还是困扰你，可以直接把样本贴在这。

**Comment by Fast12138** [comment]
sorry sorry，有人fork我的自用，所以突然改私有了。
https://raw.githubusercontent.com/Fast12138/DeathNote/main/w.js
 这次肯定没问题，顺便测试新版~

**Comment by echo094** [comment]
已修复

**Comment by Fast12138** [comment]
very nice，还增强了！之前手动解了半天。还得是大佬
