### ISSUE TITLE
obfuscator: stringArrayCallsWrapper所在的variableDeclaration存在其它变量时出现错误

### ISSUE THREAD

**Issue by Fast12138** [echo094/decode-js#111]
https://raw.githubusercontent.com/sudojia/scripts/script/sudojia_tea100.js
sojsonv7 解密之后还有一层加密，无法解密

使用网址：https://dev-coco.github.io/Online-Tools/JavaScript-Deobfuscator.html
并删除 第一层加密里的Iil1IIi() 最后可以解密成功

**Comment by echo094** [comment]
打包函数`Ililiiii`的定义和后面的内容连一起了，在生成提取代码的时候没有分开，导致多执行了后面的内容。而这部分内容中恰好有`require`，就出现了异常。

**Comment by nmyhhd** [comment]
不报错了，但解出来的代码还是无法识别

**Comment by the-best-richer** [comment]
佬，最新的版本我解密https://raw.githubusercontent.com/sudojia/scripts/refs/heads/script/sudojia_shuifei.js还是和这个issue一样的错误耶

**Comment by echo094** [comment]
> 佬，最新的版本我解密 https://raw.githubusercontent.com/sudojia/scripts/refs/heads/script/sudojia_shuifei.js 还是和这个issue一样的错误耶

这是独立的问题，可参考新issue
