### ISSUE TITLE
obfuscator: 拼接stringArray代码时因保留注释而忽略掉部分语句

### ISSUE THREAD

**Issue by djc-Sherlock** [echo094/decode-js#118]
### Which plugin are you reporting a bug for?

obfuscator

### Version of Node

18.16.4

### Input code

https://playcode.io/1977912
ob解密的时候报错了
  for (let i = bind.length - 1; i >= 0; --i) {
                    ^
TypeError: Cannot read properties of undefined (reading 'length')

**Comment by echo094** [comment]
你下载的代码是最新的吗，怎么你的报错和我的不一样

**Comment by djc-Sherlock** [comment]
> 你下载的代码是最新的吗，怎么你的报错和我的不一样

贴上去的完整代码解密也会报错。我展示的这个报错应该是第4行的加密代码解密后的报错

**Comment by echo094** [comment]
你仔细看下，报的不是同一个错。你贴出来的问题和 #116 一样。

**Comment by echo094** [comment]
处理完整代码时的报错是找不到函数名，问题出在拼接代码时混入了单行注释，导致后续代码被忽略。

你更新下最新代码，然后重新安装依赖，应该都解决了。

**Comment by djc-Sherlock** [comment]
> 处理完整代码时的报错是找不到函数名，问题出在拼接代码时混入了单行注释，导致后续代码被忽略。
> 
> 你更新下最新代码，然后重新安装依赖，应该都解决了。

已验证，没问题了，感谢

**Comment by djc-Sherlock** [comment]
> 处理完整代码时的报错是找不到函数名，问题出在拼接代码时混入了单行注释，导致后续代码被忽略。
> 
> 你更新下最新代码，然后重新安装依赖，应该都解决了。
运行解密后的脚本会报错，加密前的脚本能正常运行。这个我该如何排查问题，或者提供什么日志

**Comment by echo094** [comment]
再试下，如果还有问题就把运行报错的详细输出内容贴一下。

**Comment by djc-Sherlock** [comment]
> 再试下，如果还有问题就把运行报错的详细输出内容贴一下。

可以正常使用了，感谢
