### ISSUE TITLE
visitor(delete-unused-var): 变量使用new初始化时被删除

### ISSUE THREAD

**Issue by zhuang010203** [echo094/decode-js#120]
### Which plugin are you reporting a bug for?

sojsonv7

### Version of Node

v16.20.2

### Input code

原文：https://www.jiexiapi.top/js/jiexiapi.js
js文件中有一个请求接口函数，有参数timestamp、key字段，我想通过代码查看这2个参数是如何生成的？请问是否可以进行代码解密

**Comment by echo094** [comment]
这个解混淆本身没问题呀

**Comment by zhuang010203** [comment]
是的，解混淆，就是原文里有var app = new Vue({})，这一部分内容，output文件里没有相关的代码

**Comment by zhuang010203** [comment]
> 这个解混淆本身没问题呀



> 这个解混淆本身没问题呀


是的，解混淆，就是原文里有var app = new Vue({})，这一部分内容，output文件里没有相关的代码

**Comment by zhuang010203** [comment]
![image](https://github.com/user-attachments/assets/2885fdb7-e684-44a2-ba7f-76919660cce6)
yua原文1047行处，我想知道data的参数是通过哪些函数计算出来的

**Comment by echo094** [comment]
这是在删除未使用变量阶段被误删了，现已进一步提高删除未使用变量的条件。

**Comment by echo094** [comment]
但是你想要的`newpass`并不在这个文件里，你需要自己想办法了。
