### ISSUE TITLE
obfuscator: 解混淆string-array卡死

### ISSUE THREAD

**Issue by mrright-cyber** [echo094/decode-js#121]
大佬好，近期碰到一个js文件如：https://netcut.cn/howCanIDecode

使用了 `decode` 方式解密，无法解开。

使用了 `deob` 方式解密，如下图，一直卡着无法进行下去。
![image](https://github.com/user-attachments/assets/9d54786e-2a22-45f1-855d-7a1be844dcef)

不知道是新混淆还是bug问题，烦请大佬看看

**Comment by echo094** [comment]
这个是更新了`string-array`的模版。

`string-array`分成3个部分：

- `string-array-node`
- `string-array-rotate-function-node`
- `string-array-calls-wrapper`

这个样本进行了下述修改：

1. 修改了修改了`string-array-calls-wrapper`，在函数中引用了两次`string-array-node`
2. 修改了`string-array-rotate-function-node`的处理逻辑，在其中调用了`string-array-calls-wrapper`。

由于修改1，当前版本的工具匹配了两次`string-array-calls-wrapper`，在现有逻辑下，`string-array-calls-wrapper`会变成空函数。

由于修改2，当`string-array-calls-wrapper`出现异常时，会陷入死循环，导致工具卡死。

以更新工具以适配该特征。

**Comment by nongwoluanlai666** [comment]
哥  您把我issue的剪切板覆盖了(˘˘)
