### ISSUE TITLE
visitor(split-variable-declaration): 执行后作用域binding异常

### ISSUE THREAD

**Issue by echo094** [echo094/decode-js#124]
佬，最新的版本我解密 https://raw.githubusercontent.com/sudojia/scripts/refs/heads/script/sudojia_shuifei.js 还是和这个issue一样的错误耶

_Originally posted by @the-best-richer in https://github.com/echo094/decode-js/issues/111#issuecomment-2363278749_

**Comment by echo094** [comment]
在这个visitor中使用了`insertBefore`操作（并且插入的内容是变量声明），因此在操作完成后需要刷新作用域，否则被移动的变量将无法正确检索。

**Comment by the-best-richer** [comment]
好，谢谢echo佬
