### ISSUE TITLE
大佬，下面是加密代码地址，解密过程中间报错，能否支援一下？

### ISSUE THREAD

**Issue by greenwave1987** [echo094/decode-js#17]
https://raw.githubusercontent.com/6dylan6/jdpro/main/function/dylanz.js

**Comment by echo094** [comment]
已更新，需要调用2次obfuscator解混淆，如果还是有问题再反馈一下。

这个脚本和#15 是类似的，那个脚本可读性好一点。

**Comment by greenwave1987** [comment]
万分感谢
