### ISSUE TITLE
大佬，关于py的能解吗

### ISSUE THREAD

**Issue by xiaodan01** [echo094/decode-js#25]
exec(marshal.loads(zlib.decompress(一串代码)))这种的，py3.10以上版本，能解回去吗

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by echo094** [comment]
这是babel的ast，只适用于javascript。

marshal.loads本来就是反序列化呀，你去掉exec不就行了。
