### ISSUE TITLE
大佬麻烦看着 V7直接报错cannot find decrypt variable

### ISSUE THREAD

**Issue by shusheng110** [echo094/decode-js#28]
脚本是sojsonv7的 但是运行解密直接报错 annot find decrypt variable
![image](https://github.com/echo094/decode-js/assets/33216795/8deb1f69-81a7-47b1-99bb-63edd497ff7e)

脚本地址：https://wwi.lanzoup.com/ikSrF152kfyd

**Comment by echo094** [comment]
> 脚本地址：https://wwi.lanzoup.com/ikSrF152kfyd

这个脚本的结构比较复杂：

```mermaid
graph LR
    A[代码块1]--> F[顺序拼接]
    B[代码块2] -- V7混淆1 --> D(混淆代码1)
    C[代码块3] --V7混淆2 --> E(混淆代码2)
    D --> F
    E --> F
    F -- V7混淆3 --> G[混淆代码3]
```
而且，在进行第3次混淆的时候，可能是选择了保留变量`version_`，让最终的脚本出现了3个字符串表。
因为情况太过特殊，我现在先简单处理了一下，你试试对于这个脚本能不能正常处理。

**Comment by shusheng110** [comment]
> > 脚本地址：https://wwi.lanzoup.com/ikSrF152kfyd
> 
> 这个脚本的结构比较复杂：
> 
> ```mermaid
> graph LR
>     A[代码块1]--> F[顺序拼接]
>     B[代码块2] -- V7混淆1 --> D(混淆代码1)
>     C[代码块3] --V7混淆2 --> E(混淆代码2)
>     D --> F
>     E --> F
>     F -- V7混淆3 --> G[混淆代码3]
> ```
> 而且，在进行第3次混淆的时候，可能是选择了保留变量`version_`，让最终的脚本出现了3个字符串表。 因为情况太过特殊，我现在先简单处理了一下，你试试对于这个脚本能不能正常处理。

感谢大佬 已经试过了 确实可以解开了 也不报错  就是在移除代码不彻底了 已经很好了 非常感谢
