### ISSUE TITLE
v7解密报错

### ISSUE THREAD

**Issue by TongLin138** [echo094/decode-js#29]
代码链接：https://playcode.io/1560693
其中script.js和script2.js，都是同样错误。

#### 解密报错内容
> PS D:\Github\Decode> node src/main.js -t sojsonv7 [-i input.js] [-o output.js]
> 类型: sojsonv7
> 输入: input.js
> 输出: output.js
> 处理全局加密...
> Version var: version_
> Error: cannot find decrypt variable

**Comment by echo094** [comment]
v7部分已更新，但是这两个脚本还嵌套了一层obfuscator混淆，目前存在点问题

**Comment by TongLin138** [comment]
在经过v7部分解密后，使用 [relative/synchrony](https://github.com/relative/synchrony) 作者的 https://deobfuscate.relative.im/ 工具可以进行解密，但是可读性很低（举例：会出现解密不完全，console.log分好多行的情况），期待您进一步的支持。
```javascript
console.log(
    '触发时段:',
    _0x210cb6.map(
        (_0x370eb7) =>
        (_0x370eb7[0] < 10 ? '0' + _0x370eb7[0] : _0x370eb7[0]) +
        ':' +
        (_0x370eb7[1] < 10 ? '0' + _0x370eb7[1] : _0x370eb7[1]) +
        ':' +
        (_0x370eb7[2] < 10 ? '0' + _0x370eb7[2] : _0x370eb7[2])
    )
)
```

**Comment by echo094** [comment]
> ```js
> console.log(
>     '触发时段:',
>     _0x210cb6.map(
>         (_0x370eb7) =>
>         (_0x370eb7[0] < 10 ? '0' + _0x370eb7[0] : _0x370eb7[0]) +
>         ':' +
>         (_0x370eb7[1] < 10 ? '0' + _0x370eb7[1] : _0x370eb7[1]) +
>         ':' +
>         (_0x370eb7[2] < 10 ? '0' + _0x370eb7[2] : _0x370eb7[2])
>     )
> )
> ```

这段代码原本的逻辑就是这样的（分别给时分秒补成2位），上面工具的结果是对的。

我提到的问题是在代码块解混淆阶段错误合并了一些非混淆用的Object。

**Comment by echo094** [comment]
obfuscator解混淆应该不报错了

**Comment by TongLin138** [comment]
是的，不报错了。感谢作者❤。
