### ISSUE TITLE
sojsonv7失败

### ISSUE THREAD

**Issue by aizyxaizyx** [echo094/decode-js#3]
sojsonv7解出来是个0kb的空文件

**Comment by echo094** [comment]
这个脚本在格式化后可发现是由3个部分组成：

```javascript
// Part1
var _adsData = {};
// Part2
(function () {
  var _20 = "jsjiami.com.v6"
})();
// Part3
var version_ = "jsjiami.com.v7";
```

第一部分未混淆，第二部分函数中的内容使用了**jsjiami.com.v6**混淆，剩余的第三部分使用了**jsjiami.com.v7**混淆。
将上述混淆的部分单独复制出来解密即可。

需要注意必须要将每段混淆代码的版本定义放到第一行：

* var _20='jsjiami.com.v6', ...
* var version_='jsjiami.com.v7';
