### ISSUE TITLE
ob类的解了之后好像会运行不起来

### ISSUE THREAD

**Issue by xiaodan01** [echo094/decode-js#30]
大佬，ob的解密之后感觉像是删多了代码，运行不起来报错
这是源代码

**Comment by echo094** [comment]
> 大佬，ob的解密之后感觉像是删多了代码，运行不起来报错 这是源代码https://note.ms/jpva

报错也贴一下，我这能运行到`未找到CK`。

**Comment by xiaodan01** [comment]
![image](https://github.com/echo094/decode-js/assets/65934452/1f7db17a-b473-419b-ab2f-3a05994ee4b7)

**Comment by echo094** [comment]
<img width="487" alt="Screenshot 2023-08-24 at 21 44 18" src="https://github.com/echo094/decode-js/assets/20028238/99979d84-0908-465b-8bd3-f4b4163e8030">

我用原始（混淆过的）脚本跑也是一样的问题，说明不是解混淆的问题哈。

事实上这个脚本在混淆的时候忘记选择保留变量**CryptoJS**了，你看看有没有更新过的。

**Comment by xiaodan01** [comment]
嘶，好的，我去看看，
