### ISSUE TITLE
大佬，麻烦抽空看看看看这个啥原因吧。

### ISSUE THREAD

**Issue by greenwave1987** [echo094/decode-js#32]
类型: sojsonv7
输入: input.js
输出: output.js
处理全局加密...
Version var: version_
Unexpected ref var_version: "ver": version_
Cannot find string table

已经解决了，加密文件开头结尾都是var version_='jsjiami.com.v7';用npm run deob可以。不用能npm run desov7

**Comment by echo094** [comment]
是这样的，这个version_就是迷惑用的，脚本中没有任何sojsonv7的特征。

这个脚本昨天还不是这样的，更新的有点快啊。
