### ISSUE TITLE
obfuscator类型解除环境限制规则有点宽松

### ISSUE THREAD

**Issue by cesaryuan** [echo094/decode-js#34]
实例代码：https://gist.github.com/cesaryuan/15094ba48aad960fe7c993d7bbd1597e/raw/16162c5a5ddfc82e26e63e99fdf641f306aca0c1/sample.js

运行`npm run deob`后只剩下一行：`'use strict';`

**Comment by echo094** [comment]
这个插件是我在别人的代码上，结合之前写的sojson插件，一步步完善改过来的。**解除环境限制**里面的这个方法一直没有人反馈过有问题，所以到现在还是最原始的样子（我也不知道Obfuscator究竟有哪些调试限制）。

我先禁用了，有空了先研究一下，或者等别人反馈了再说。

**Comment by echo094** [comment]
可以测试一下这个PR

**Comment by cesaryuan** [comment]
[test.txt](https://github.com/echo094/decode-js/files/12901442/test.txt)

谢谢大佬，这个好像会报错

**Comment by echo094** [comment]
> [test.txt](https://github.com/echo094/decode-js/files/12901442/test.txt)

报错的部分已修复，目前还有个ConsoleOutputDisable类型的代码没有被删除

**Comment by echo094** [comment]
ConsoleOutputDisable类型的移除已添加，再测试一下吧
