### ISSUE TITLE
我可以提一个PR把esmodule模式改成cjs模式吗

### ISSUE THREAD

**Issue by cesaryuan** [echo094/decode-js#36]
es module的问题在于用vscode或者webstorm调试时不支持在uncaught exception处断下来，不利于调试（在尝试为decode-js做贡献，但是发现不支持异常断点调试起来好麻烦哈哈）

而cjs则没有这个问题，所以想问下大佬我可以提一个pr改成cjs模式嘛

**Comment by echo094** [comment]
欢迎

**Comment by cesaryuan** [comment]
> 欢迎，但是工作量看起来有点大啊。

看了下还行，要改的不算多好像

**Comment by cesaryuan** [comment]
> 你顺便把文件后缀改成cjs吧。

这个感觉不用改也行，改了之后pr会一片红🤣

**Comment by echo094** [comment]
我找到一个新的方案 https://github.com/nodejs/node/issues/50430#issuecomment-2449419913
