### ISSUE TITLE
大佬有空看看这个吧，解密不完全。

### ISSUE THREAD

**Issue by greenwave1987** [echo094/decode-js#42]
https://raw.githubusercontent.com/6dylan6/jdpro/main/jx_cxjhelp.js

**Comment by TongLin138** [comment]
你好：
在这次[commit](https://github.com/echo094/decode-js/commit/8313b600af7dc096f9de05c10069d6eea93a078a)中，作者关掉了解除环境限制的功能，导致部分代码没有完全解密。只要将这两行恢复即可全部解密。

**Comment by echo094** [comment]
已修复，但由于#34 的问题，目前代码中的防格式化语句未移除，可手动查找代码中的`debugger`和`RegExp`移除。
