### ISSUE TITLE
sojson类型解除自卫模式和禁止控制台调试失效

### ISSUE THREAD

**Issue by GameAttacker** [echo094/decode-js#45]
https://playcode.io/1628267

有v7标志，但是不是官方那种带v7结尾的

**Comment by echo094** [comment]
这代码本身就无法正常运行啊，有没有格式化前的版本

**Comment by GameAttacker** [comment]
在网址里面，有个原版.js文件

**Comment by echo094** [comment]
> https://playcode.io/1628267
> 
> 有v7标志，但是不是官方那种带v7结尾的

一共3行，都是sojson类型的。

但是保护性的代码没有被正确移除，我去看下是不是特征更新了。

**Comment by echo094** [comment]
试一下分支 https://github.com/echo094/decode-js/tree/fix_sojson

**Comment by GameAttacker** [comment]
![image](https://github.com/echo094/decode-js/assets/42198201/7529bd5d-f800-4ec6-a99b-b763b420e943)

这是先common，再v7解密的报错

**Comment by GameAttacker** [comment]
用sojson/deso可以解密，用v7不行，感谢大佬

**Comment by echo094** [comment]
代码是`sojson`类型，不是`sojsonv7`类型。还有这个代码不需要也不能先运行`common`（会格式化，导致sojson插件在解全局混淆时无法通过自保护检测）

**Comment by GameAttacker** [comment]
是的，直接sojson解了，谢谢大佬
