### ISSUE TITLE
不知道是什么方式的怎么办

### ISSUE THREAD

**Issue by getr00t** [echo094/decode-js#5]
有一个js我试了下使用你这个工具，把里面全部type类型的方式都测试过，都报错，请问还有希望吗？完全看不出是什么类型方式的

**Comment by echo094** [comment]
可以把文件发一下

**Comment by echo094** [comment]
这可能是Obfuscator的改良版，它将部分定义语句合并到了一个定义列表里，让现有的匹配方式失效了。

**Comment by echo094** [comment]
你确定上传的脚本是未经修改过的吗，我放青龙里都运行不了呀，不能正常运行的脚本是没法正确进行ast分析的。
我觉得你是不是把第二行末尾的分号改成逗号了，导致函数定义语句变成了表达式语句，使第四行的函数未定义了。

**Comment by echo094** [comment]
更新了，你用没有逗号的版本试一下吧

**Comment by echo094** [comment]
> > 更新了，你用没有逗号的版本试一下吧
> 
> 更新了你的新版本，可以分析出来了，但是拿分析的文件反而在本地node环境下运行失败，神奇，反而报错ReferenceError: _0x31de is not defined。

漏删了一些混淆变量，你再试试
