### ISSUE TITLE
sojsonv7: 排序函数模版更新后无法识别

### ISSUE THREAD

**Issue by Colorsssss** [echo094/decode-js#51]
脚本
>https://github.com/shufflewzc/faker2/blob/main/jd_dongDongFarm_task.js

> 类型: sojsonv7
> 输入: F:\decode-js-main\2.js
> 输出: jd_dongDongFarm_task.js
> 处理全局加密...
> Version var: version_
> Unexpected ref var_version: version_ = l1Ilil(891, "!vXI")
> 主加密变量: IlIIliil
> Go to sub: l1Ilil
> Go to sub: IIllilIl
> Go to sub: lIli1i1i
> Go to sub: IIiIIll
> Go to sub: lI1l1i1I
> Go to sub: iiIIIII1
> Go to sub: IlIi1llI
> 
> F:\decode-js-main\node_modules\vm2\lib\vm.js:287
>                                 throw bridge.from(e);
>                                 ^
> URIError [Error]: URI malformed
>     at decodeURIComponent (<anonymous>)
>     at _0x5e2231 (vm.js:1:18962)
>     at Function._0x3b8d00 [as aYZHND] (vm.js:1:19102)
>     at IlIIliil (vm.js:1:20145)
>     at IlIIliil (vm.js:1:20231)
>     at vm.js:1:1
>     at Script.runInContext (node:vm:140:12)
>     at VM.runScript (F:\decode-js-main\node_modules\vm2\lib\vm.js:285:18)
>     at VM.run (F:\decode-js-main\node_modules\vm2\lib\vm.js:503:16)
>     at virtualGlobalEval (F:\decode-js-main\src\plugin\sojsonv7.js:18:14)
>

**Comment by echo094** [comment]
已修复
