### ISSUE TITLE
other: @babel/parser RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by XZ1314XZ** [echo094/decode-js#53]
大佬，请帮忙看看。https://playcode.io/1651779

**Comment by echo094** [comment]
这个脚本并不属于列表中的某个混淆方式，而是使用了和 #35 一样的混淆器。

这个错误是eval中的代码层数太多，使@babel/parser插件无法解析AST，并不是这个项目的问题。

如果你能够提供这个混淆器的更多信息，我可以帮你找一下有没有相应的工具，或者为这个工具写一个插件。

**Comment by echo094** [comment]
已添加对应的插件。
