### ISSUE TITLE
这个是什么类型的

### ISSUE THREAD

**Issue by getr00t** [echo094/decode-js#6]
这个是什么类型的使用工具无法解出来尼

**Comment by echo094** [comment]
这也是Obfuscator，但是这个脚本可能被错误格式化了，导致运算符`?.`([Optional chaining](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining))中间被加了空格，就变成了`?`([Conditional (ternary) operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Conditional_operator))加`.`，让AST无法正确生成语法树，也就是在正式分析前就发生异常结束了。

例如第117行：
```javascript
    _0x299db7[_0x3d58d9(0x31b) + '\x64'] = _0x299db7 ? . [_0x3d58d9(0x31b) + '\x64'] ? . [_0x3d58d9(0x1e0) + '\x65\x72\x43\x61\x73' + '\x65']() || _0x468f39[_0x3d58d9(0x393)];

```
正确的写法：
```javascript
    _0x299db7[_0x3d58d9(0x31b) + '\x64'] = _0x299db7 ?. [_0x3d58d9(0x31b) + '\x64'] ?. [_0x3d58d9(0x1e0) + '\x65\x72\x43\x61\x73' + '\x65']() || _0x468f39[_0x3d58d9(0x393)];
```

你再确认一下这个脚本能不能运行，然后用格式化前的版本解混淆。

也可以先把`? .`中的空格去掉再解混淆。

**Comment by echo094** [comment]
整个脚本原版应该在 leafTheFish/DeathNote@62dfc9523da40ffa9e89263e968caf9e6caeeb64，是sfsyV2.js，这个版本是没问题的。

**Comment by echo094** [comment]
这种混淆过的脚本就别格式化了，解出来的能用就别去管了。

我的配置文件已经在仓库里了：[.eslintrc.json](https://github.com/echo094/decode-js/blob/bf4740305e1babe1822c0f93f76dea2f36ca0994/.eslintrc.json)，这个`?.`是**ecmascript 2020**的新特性，如果你配置文件里的版本较低，应该会报错。

**Comment by echo094** [comment]
我把discussions开了，可以在那边讨论哈。

**Comment by echo094** [comment]
1. 这个是sojson类型的，你用错插件了。
2. 要把第二行拿出来解混淆，和#4 一样，不然会产生干扰。
3. 这个脚本经过了两次sojson类型的混淆，所以你在第一次输出的代码上再解混淆一次。
