### ISSUE TITLE
obfuscator: 在 #55 后失效

### ISSUE THREAD

**Issue by goodwenhao** [echo094/decode-js#60]
https://raw.githubusercontent.com/goodwenhao/study/main/test.js

**Comment by goodwenhao** [comment]
类型: obfuscator
输入: input.js
输出: output.js
还原数值...
处理全局加密...
Try v3 mode...
Try v2 mode...
Essential code missing!
Cannot find string list!

**Comment by echo094** [comment]
更新 9a673d84c135b4cfa920d7ba9bba0e426fc9463c #55 完善了对rotate函数的识别方式（过去只进行了简单的匹配），这也导致新的函数不再能够识别未被支持的版本。

这个脚本使用的版本比较古老，在 javascript-obfuscator/javascript-obfuscator@efac711ce40cea34cb2747ba6bba9b7385667c6e (2.10.0) 之前，rotate函数相较于后续版本更为简洁。

近期修复。
