### ISSUE TITLE
sojsonv7: 版本更新后无法识别rotateFunction

### ISSUE THREAD

**Issue by xiaodan01** [echo094/decode-js#62]
Try v3 mode...
Try v2 mode...
Essential code missing!
Cannot find string list!

**Comment by echo094** [comment]
贴个代码

**Comment by xiaodan01** [comment]
https://note.ms/jpva

**Comment by echo094** [comment]
> https://note.ms/jpva

里面是空的呀

**Comment by xiaodan01** [comment]
昂，我以为昨天看过了，我就给清空了。我现在放一下



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: echo094 ***@***.***&gt;
发送时间: 2023年11月22日 15:18
收件人: echo094/decode-js ***@***.***&gt;
抄送: xiaodan01 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [echo094/decode-js] 好像这次更新之后还有这个问题 (Issue #62)

**Comment by echo094** [comment]
这个脚本很有意思，应该是在obfuscator的基础上自己魔改了，在obfuscator的记录里没有这种格式。

**Comment by xiaodan01** [comment]
这么牛，是不是没办法了



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: echo094 ***@***.***&gt;
发送时间: 2023年11月22日 15:39
收件人: echo094/decode-js ***@***.***&gt;
抄送: xiaodan01 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [echo094/decode-js] 好像这次更新之后还有这个问题 (Issue #62)





 
这个脚本很有意思，应该是在obfuscator的基础上自己魔改了，在obfuscator的记录里没有这种格式。

**Comment by echo094** [comment]
适配下就行

**Comment by xiaodan01** [comment]
牛



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: echo094 ***@***.***&gt;
发送时间: 2023年11月22日 15:41
收件人: echo094/decode-js ***@***.***&gt;
抄送: xiaodan01 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [echo094/decode-js] 好像这次更新之后还有这个问题 (Issue #62)





 
适配下就行

**Comment by echo094** [comment]
方向错了，这个脚本是用最新sojsonv7混淆的，不是obfuscator。

**Comment by xiaodan01** [comment]
但是我用v7也解不了，会报错



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: echo094 ***@***.***&gt;
发送时间: 2023年11月22日 15:56
收件人: echo094/decode-js ***@***.***&gt;
抄送: xiaodan01 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [echo094/decode-js] obfuscator: stringArrayV3无法识别魔改版本 (Issue #62)





 
方向错了，这个脚本是用最新sojsonv7混淆的，不是obfuscator。

**Comment by echo094** [comment]
> 但是我用v7也解不了，会报错

因为他更新了，特征和之前不一样了。你可以去混淆一个脚本，会报一样的错误。

**Comment by xiaodan01** [comment]
应该能更新解决吧



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: echo094 ***@***.***&gt;
发送时间: 2023年11月22日 16:02
收件人: echo094/decode-js ***@***.***&gt;
抄送: xiaodan01 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [echo094/decode-js] sojsonv7: 版本更新后无法识别rotateFunction (Issue #62)





  
但是我用v7也解不了，会报错
  
因为他更新了，特征和之前不一样了。你可以去混淆一个脚本，会报一样的错误。

**Comment by echo094** [comment]
> 应该能更新解决吧

可以，但我打算等几天，看看他会不会再更新。

**Comment by xiaodan01** [comment]
好的大佬



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: echo094 ***@***.***&gt;
发送时间: 2023年11月22日 16:05
收件人: echo094/decode-js ***@***.***&gt;
抄送: xiaodan01 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [echo094/decode-js] sojsonv7: 版本更新后无法识别rotateFunction (Issue #62)





  
应该能更新解决吧
  
可以，但我打算等几天，看看他会不会再更新。
