### ISSUE TITLE
sojsonv7出错

### ISSUE THREAD

**Issue by dslll** [echo094/decode-js#65]
https://playcode.io/1674603
sojsonv7的报错如下
![image](https://github.com/echo094/decode-js/assets/110463632/15fdaed5-470d-47fe-9ed4-54d8b65477e9)

所有模式都试过了，解不了。
大佬这种的应该怎么解啊

**Comment by echo094** [comment]
链接是不是错了，里面的代码不是截图里的呀

**Comment by dslll** [comment]
里面的测试.js是的
![0345e8dc21b6e7bead2f8743d77640e4](https://github.com/echo094/decode-js/assets/110463632/283ea9bc-1291-44d7-a577-4c025d1a49b6)

**Comment by echo094** [comment]
这个`测试.js`里面，根本没有截图里的变量`_0x465f`呀。

还有，你是不是没有更新到最新版 4985fac3e4641ed2bfd6fbff49120eb57ef6cd02

**Comment by dslll** [comment]
不好意思，应该是我放错代码了，但加密方法都是一样的。
真对不起哇哇哇哇，我没注意到更新最新版。。。。
现在能正常解密了，非常感谢大佬的耐心回复！
<img width="274" alt="image" src="https://github.com/echo094/decode-js/assets/110463632/c34900ed-9ebb-496e-9e4f-d431d1bf6adb">
