### ISSUE TITLE
sojsonv7: string-array与version在一行定义中时出错

### ISSUE THREAD

**Issue by goodwenhao** [echo094/decode-js#66]
https://github.com/goodwenhao/study/raw/main/test.js

**Comment by echo094** [comment]
你是否知道这个代码大概是什么日期的呢

**Comment by goodwenhao** [comment]
> 你是否知道这个代码大概是什么日期的呢

今年3月份的

**Comment by echo094** [comment]
sojsonv7的问题解决了，但这个代码还嵌套了一层obfuscator混淆，这个目前还有问题

**Comment by goodwenhao** [comment]
好的，v7可以了，辛苦佬

**Comment by echo094** [comment]
obfuscator插件已更新
