### ISSUE TITLE
other: 混淆方式定位问题

### ISSUE THREAD

**Issue by XZ1314XZ** [echo094/decode-js#68]
https://playcode.io/1679298

**Comment by XZ1314XZ** [comment]
请求大佬帮忙看看

**Comment by echo094** [comment]
> https://playcode.io/1679298

如果你指的是里面那个以`var _0xodN='danchaofan';`开头的代码，你需要使用sojsonv7。

**Comment by XZ1314XZ** [comment]
非常感谢。这个跟jsjiamiv7特征不明显，我没有预料到
