### ISSUE TITLE
jjencode: Cannot find variable name!

### ISSUE THREAD

**Issue by xiaodan01** [echo094/decode-js#69]
https://note.ms/rxiz

**Comment by echo094** [comment]
> https://note.ms/rxiz

我试了下这里面的代码没问题啊

**Comment by xiaodan01** [comment]
咦，奇怪了，我这边咋就报错呢Cannot find variable name!，我在重新拉一下，重新装一遍依赖试试

**Comment by xiaodan01** [comment]
删掉注释正常了，，，我这边的源代码有注释，，，
