### ISSUE TITLE
sojsonv7: decode local object failed

### ISSUE THREAD

**Issue by xiaodan01** [echo094/decode-js#72]
https://note.ms/imos

**Comment by echo094** [comment]
> https://note.ms/imos

在ob后还需要进行一次sojsonv7处理，但目前有个小bug要修一下。

**Comment by xiaodan01** [comment]
ob以后，在v7处理，可读性也是很差。跟之前差的有点多，难不成是因为他进行了多次处理





------------------ Original ------------------
From: echo094 ***@***.***&gt;
Date: Mon,Feb 19,2024 4:12 PM
To: echo094/decode-js ***@***.***&gt;
Cc: xiaodan01 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [echo094/decode-js] sojsonv7: decode local object failed (Issue#72)





  
https://note.ms/imos
  
在ob后还需要进行一次sojsonv7处理，但目前有个小bug要修一下。

**Comment by echo094** [comment]
已修复

**Comment by xiaodan01** [comment]
大佬牛皮，给个好友位吧，赞助一下，这么辛苦

**Comment by echo094** [comment]
不用，出于安全考虑，本账号下的项目不接受任何形式的赞助。

我个人觉得sojson系列以后不太可能有大更新了，毕竟他的爹obfuscator已经停更快半年了。
