### ISSUE TITLE
obfuscator: 使用低版本(<0.22.0)以及eval包装

### ISSUE THREAD

**Issue by huanzhiyi** [echo094/decode-js#77]
https://raw.githubusercontent.com/MrGao-Prog/rdfplayer/main/js/RdfPlayer.min.js

类型: obfuscator
还原数值...
处理全局加密...
Try v3 mode...
Try v2 mode...
Essential code missing!
Cannot find string list!

**Comment by echo094** [comment]
两个条目需要适配：

1. 将代码当作字符串进行进一步编码，随后交给eval执行
2. 使用了旧版本的obfuscator，时间早于commit javascript-obfuscator/javascript-obfuscator@3a1cc4e4f5f0c172448fa268b4f415fdee805c4f (0.22.0)。上述版本中变量kind都为`var`，后续版本则会将常量改为`constant`

**Comment by echo094** [comment]
已修复，见LOG：

[log_77_1.txt](https://github.com/echo094/decode-js/files/14545232/log_77_1.txt)

**Comment by huanzhiyi** [comment]
好的 去测试一下 🙏🏻
