### ISSUE TITLE
sojsonv7: 当rotateFunction不在SequenceExpression中时无法被执行

### ISSUE THREAD

**Issue by xiaodan01** [echo094/decode-js#78]
https://note.ms/wbgc

**Comment by xiaodan01** [comment]
> https://note.ms/wbgc

这个是v7的时候
![image](https://github.com/echo094/decode-js/assets/65934452/26897073-7d66-4147-b43d-d480a5217430)

**Comment by xiaodan01** [comment]
另外一个https://note.ms/txqi
ob的时候
![image](https://github.com/echo094/decode-js/assets/65934452/ce39296c-84b8-482c-8afc-509afd30a481)

**Comment by xiaodan01** [comment]
嗯

**Comment by echo094** [comment]
> 另外一个https://note.ms/txqi ob的时候 ![image](https://private-user-images.githubusercontent.com/65934452/310153590-ce39296c-84b8-482c-8afc-509afd30a481.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk5Nzg3MjEsIm5iZiI6MTcwOTk3ODQyMSwicGF0aCI6Ii82NTkzNDQ1Mi8zMTAxNTM1OTAtY2UzOTI5NmMtODRiOC00ODJjLThhZmMtNTA5YWZkMzBhNDgxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA5VDEwMDAyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTllNDExYmM1ODI2Y2MwNmRmYmEwMWE1MmI4ZTU1MjVhODk0MWY1MjNhMDM5NzdlMzIxZTMxOTMwM2MzODIyZWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vuebcEOpY4XH1i6_TgR90l1Ewk3HuK2l4AbzXMFQfEY)

这个问题已解决。

**Comment by xiaodan01** [comment]
> > 另外一个https://note.ms/txqi ob的时候 ![image](https://private-user-images.githubusercontent.com/65934452/310153590-ce39296c-84b8-482c-8afc-509afd30a481.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk5Nzg3MjEsIm5iZiI6MTcwOTk3ODQyMSwicGF0aCI6Ii82NTkzNDQ1Mi8zMTAxNTM1OTAtY2UzOTI5NmMtODRiOC00ODJjLThhZmMtNTA5YWZkMzBhNDgxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA5VDEwMDAyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTllNDExYmM1ODI2Y2MwNmRmYmEwMWE1MmI4ZTU1MjVhODk0MWY1MjNhMDM5NzdlMzIxZTMxOTMwM2MzODIyZWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vuebcEOpY4XH1i6_TgR90l1Ewk3HuK2l4AbzXMFQfEY)
> 
> 这个问题已在处理 #77 时解决。

那个v7好像有时候可以有时候就报错那个url

**Comment by echo094** [comment]
确实格式有点细微调整，已修复：
[log_78_1.txt](https://github.com/echo094/decode-js/files/14546026/log_78_1.txt)

**Comment by xiaodan01** [comment]
> 确实格式有点细微调整，已修复：
> [log_78_1.txt](https://github.com/echo094/decode-js/files/14546026/log_78_1.txt)

感谢大佬
