### ISSUE TITLE
请大佬帮忙看下这个obfuscator类型的为什么解密不了

### ISSUE THREAD

**Issue by ldzhjn** [echo094/decode-js#8]
Log:
类型: obfuscator
输入: input.js
输出: output.js
还原数值...
处理全局加密...

node:internal/process/esm_loader:42
      internalBinding('errors').triggerUncaughtException(
                                ^
ReferenceError [Error]: _0x22ca is not defined

Node.js v20.2.0

提示_0x22ca未定义
但是源代码里第一行就是 var _0x22ca =

**Comment by echo094** [comment]
这个不太像obfuscator混淆：

1. 正常的obfuscator混淆会把字符串表包在一个函数里，这个样本没有
2. 在使用obfuscator脚本强行执行全局解混淆后，还有大量的其它混淆内容

**Comment by ldzhjn** [comment]
应该是用obfuscator混淆的
https://github.com/javascript-obfuscator/javascript-obfuscator/

我对照了这个博客里代码 基本上格式一致
https://zhuanlan.zhihu.com/p/411414106

**Comment by ldzhjn** [comment]
> 在使用obfuscator脚本强行执行全局解混淆后，还有大量的其它混淆内容
请问这个怎么操作呢？

**Comment by echo094** [comment]
你先用更新的版本看一下效果

**Comment by echo094** [comment]
使用obfuscator解混淆后得到的东西应该是Webpack bundle，你可以试一下[debundle](https://github.com/1egoman/debundle)，可能需要这个项目里的其它文件配合才行。
