### ISSUE TITLE
obfuscator: 部分局部代码块未能得到处理

### ISSUE THREAD

**Issue by xiaodan01** [echo094/decode-js#80]
https://note.ms/xoej

**Comment by echo094** [comment]
> https://note.ms/xoej

你这个样本是不是有问题，运行不了，有变量未定义：

```
星火学苑 开始运行：

ReferenceError: _0x40235b is not defined
```

我看了一下问题就是出在这里，其它内容在使用两次obfuscator插件后没问题。

**Comment by xiaodan01** [comment]
> > https://note.ms/xoej
> 
> 你这个样本是不是有问题，运行不了，有变量未定义：
> 
> ```
> 星火学苑 开始运行：
> 
> ReferenceError: _0x40235b is not defined
> ```
> 
> 我看了一下问题就是出在这里，其它内容在使用两次obfuscator插件后没问题。

咦，不是吧，我运行没问题呢，我再看看

**Comment by echo094** [comment]
> > > https://note.ms/xoej
> > 
> > 
> > 你这个样本是不是有问题，运行不了，有变量未定义：
> > ```
> > 星火学苑 开始运行：
> > 
> > ReferenceError: _0x40235b is not defined
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 我看了一下问题就是出在这里，其它内容在使用两次obfuscator插件后没问题。
> 
> 咦，不是吧，我运行没问题呢，我再看看

你这个样本被篡改过，原始版本 [星火学苑.js](https://github.com/Huansheng1/my-qinglong-js/blob/main/%E6%98%9F%E7%81%AB%E5%AD%A6%E8%8B%91.js) 里面这个变量是有被定义的

**Comment by xiaodan01** [comment]
> > > > https://note.ms/xoej
> > > 
> > > 
> > > 你这个样本是不是有问题，运行不了，有变量未定义：
> > > ```
> > > 星火学苑 开始运行：
> > > 
> > > ReferenceError: _0x40235b is not defined
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 我看了一下问题就是出在这里，其它内容在使用两次obfuscator插件后没问题。
> > 
> > 
> > 咦，不是吧，我运行没问题呢，我再看看
> 
> 你这个样本被篡改过，原始版本 [星火学苑.js](https://github.com/Huansheng1/my-qinglong-js/blob/main/%E6%98%9F%E7%81%AB%E5%AD%A6%E8%8B%91.js) 里面这个变量是有被定义的

那真是很奇怪了，麻烦大佬了，这条is都删了吧😅

**Comment by echo094** [comment]
<img width="1165" alt="image" src="https://github.com/echo094/decode-js/assets/20028238/2c75ff00-5a2b-486f-bea2-311407825dc1">

这个灰色的地方少了一个字节
