### ISSUE TITLE
jsjiami v7挂了

### ISSUE THREAD

**Issue by black-fruit** [echo094/decode-js#81]

**Comment by echo094** [comment]
贴个样本吧

**Comment by echo094** [comment]
> 连官网加密例子都解不了，也有可能是我选择有问题，但是我所有插件试一遍都没解开，二次封装的在线的那个挂掉了

在线的那个不是我在维护，你可以直接联系那个开发者。

你可以按照Readme，下载并使用sojsonv7方式处理代码。
