### ISSUE TITLE
npm i 安装依赖报错

### ISSUE THREAD

**Issue by greenwave1987** [echo094/decode-js#88]
PS E:\decode-js-1> npm i
npm ERR! code CERT_HAS_EXPIRED
npm ERR! errno CERT_HAS_EXPIRED
npm ERR! request to https://registry.npm.taobao.org/yallist/-/yallist-4.0.0.tgz failed, reason: certificate has expired

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\YXL\AppData\Local\npm-cache\_logs\2024-04-24T08_45_10_645Z-debug-0.log

**Comment by echo094** [comment]
淘宝源的问题，证书过期了，换个源吧。
