### ISSUE TITLE
这段无法解密

### ISSUE THREAD

**Issue by aizyxaizyx** [echo094/decode-js#9]
https://oss.xingxingyunpan.com/files%2F5248%2Finput.js?Expires=1687663446

**Comment by echo094** [comment]
> https://oss.xingxingyunpan.com/files%2F5248%2Finput.js?Expires=1687663446

混淆代码外边套了个函数，先要把它去掉：

```javascript
(function(){
// 这里面的是需要保留的
// var _20='jsjiami.com.v6' ... _20='jsjiami.com.v6';
})();
```

**Comment by echo094** [comment]
这段代码的功能是开控制台就卡死，全删了就行
