### ISSUE TITLE
新加密方式讨论

### ISSUE THREAD

**Issue by TongLin138** [echo094/decode-js#90]
作者您好，在GitHub上发现此加密方式，不知是否属于该项目支持加密类型（obfuscator）的变种。
https://github.com/3Kmfi6HP/EDtunnel/blob/trojan/_worker.js

**Comment by echo094** [comment]
我觉得这个文件没有经过太复杂的混淆，主要就是简化了一下变量名。

你可以对比文件末尾提到的两个文件：

* https://github.com/remorses/esbuild-plugins/blob/master/node-globals-polyfill/Buffer.js
* https://github.com/emn178/js-sha256/blob/master/build/sha256.min.js

里面的函数和字符串都维持原有的结构。
