### ISSUE TITLE
Cannot parse code: InvalidOrUnexpectedToken

### ISSUE THREAD

**Issue by GithubRookieZ** [echo094/decode-js#91]
I want to anti-obfuscate a JS file, but prompt that the error is Cannot parse code: InvalidOrUnexpectedToken. How can I solve this situation?

![微信图片_20240512100508](https://github.com/echo094/decode-js/assets/106382938/132c0233-212c-4fd2-a348-20fcbf49f708)

**Comment by echo094** [comment]
This message indicates that the **@babel/parser** plugin cannot process your file correctly, and it throws the **InvalidOrUnexpectedToken** error:

https://github.com/babel/babel/blob/1199e6aca1df0db81074cc99fa3f89a54f02810d/packages/babel-parser/src/tokenizer/index.ts#L1051-L1057

The possible reason is that the file was edited accidentally, e.g., the insertion of extra characters. The @babel/parser cannot process a code block that is unable to run properly.
