### ISSUE TITLE
ob的有个报错

### ISSUE THREAD

**Issue by xiaodan01** [echo094/decode-js#92]
throw new ReferenceError("Container is falsy");
    ^
ReferenceError: Container is falsy
代码
https://note.ms/zbtr

**Comment by echo094** [comment]
我这运行正常啊，这个报错能更详细点吗

**Comment by xiaodan01** [comment]
![image](https://github.com/echo094/decode-js/assets/65934452/afeb5df4-4ba9-40da-8ae0-67f9394525bd)

**Comment by xiaodan01** [comment]
我npm更新了下依赖可以了。。。
