### ISSUE TITLE
obfuscator: 无法正确处理stringArray的调用

### ISSUE THREAD

**Issue by jinshuqishi2019** [echo094/decode-js#94]
`npm run decode -- -t obfuscator`运行后可读性还是很差，可否进一步提高可读性？
[代码地址](https://note.ms/odza)

**Comment by echo094** [comment]
这个文件里面stringArray相关的链式调用无法被当前模版匹配，需要适配一下

**Comment by echo094** [comment]
已修复。

Note:

正常情况下，在局部空间中对stringArray的调用有两种形式：

- [StringArrayScopeCallsWrapperFunctionNode](https://github.com/javascript-obfuscator/javascript-obfuscator/blob/master/src/custom-nodes/string-array-nodes/StringArrayScopeCallsWrapperFunctionNode.ts)
- [StringArrayScopeCallsWrapperVariableNode](https://github.com/javascript-obfuscator/javascript-obfuscator/blob/master/src/custom-nodes/string-array-nodes/StringArrayScopeCallsWrapperVariableNode.ts)

其中，StringArrayScopeCallsWrapperFunctionNode是以FunctionDeclaration定义的。但是在本样本中，该类型的Node被后处理成VariableDeclarator的形式，使得现有代码无法匹配。
