### ISSUE TITLE
obfuscator: 无法处理魔改后的DebugProtectionFunctionInterval

### ISSUE THREAD

**Issue by xiaodan01** [echo094/decode-js#95]
![image](https://github.com/echo094/decode-js/assets/65934452/bf78a991-f778-4d44-85dd-ffc8a8290a29)
样本：https://note.ms/oxct

**Comment by echo094** [comment]
观察了一下样本代码，原始的混淆工具对于DebugProtection函数的调用是直接使用setInterval，但是该样本自己定义了一个myInterval函数并调用，使得匹配失效。

考虑到这项更改不属于[javascript-obfuscator](https://github.com/javascript-obfuscator/javascript-obfuscator)主线更新，计划采用保守方式进行适配，即只删除具体调用，不删除myInterval相关内容。

**Comment by echo094** [comment]
已适配。

进一步观察样本可以发现myInterval函数的定义是在单独的一行，所以极有可能是手动修改的。
