### ISSUE TITLE
obfuscator: 未知变种 寻求来源后适配

### ISSUE THREAD

**Issue by Cocoyamnut** [echo094/decode-js#97]
![image](https://github.com/echo094/decode-js/assets/99504275/6c184441-6a82-404b-9992-56c24fea70f4)
[样本](https://note.ms/oxtj)

**Comment by echo094** [comment]
更新下代码

**Comment by echo094** [comment]
是更新下这个工具的代码，最新代码的第254行不是你截图中的内容

**Comment by echo094** [comment]
你现在用的是**obfuscator_variant**分支，这个是专门针对 #74 的版本的，你切换到**main**分支就行

**Comment by echo094** [comment]
main分支的254行是下面这个，你明显没切过去，删了重新下吧

https://github.com/echo094/decode-js/blob/478ced8cdb45f9e4f6fa0983b1dd3f45fc5fd674/src/plugin/obfuscator.js#L250-L255

**Comment by echo094** [comment]
> https://note.ms/oxtj

这个样本的后处理有点多，不太好适配
