### ISSUE TITLE
obfuscator: 未知变种 寻求来源后适配

### ISSUE THREAD

**Issue by woshicaca** [echo094/decode-js#98]
[idasd.txt](https://github.com/user-attachments/files/15835207/idasd.txt)
这个无法解，麻烦看一下

**Comment by echo094** [comment]
1. 这个和正版的obfuscator区别很大，基本不考虑通过修改现有插件的方式适配
2. 最近也有其它人报告过，怀疑是出了一个新的混淆工具，方便的话可以提供一下样本的来源

**Comment by echo094** [comment]
进一步测试表明这个样本先进行了一次V7混淆，然后进行了一次自定义混淆

**Comment by woshicaca** [comment]
> 进一步测试表明这个样本先进行了一次V7混淆，然后进行了一次自定义混淆

麻烦你了

**Comment by echo094** [comment]
链接 #96 具有同样的forStatement代替whileStatement特征
