### ISSUE TITLE
obfuscator: An error occurred while handling BlockStatementControlFlowFlatteningNode

### ISSUE THREAD

**Issue by peasshoter** [echo094/decode-js#99]
[index.txt](https://github.com/user-attachments/files/15846055/index.txt)
清理死代码...
扁平化还原: _0x4924e0[_0x3fb2a9]就报错
for (let i = 0; i < pre_path.node.declarations.length; ++i) {
                                                   ^
TypeError: Cannot read properties of undefined (reading 'length')

**Comment by echo094** [comment]
已修复。

Note:

在查找BlockStatementControlFlowFlatteningNode的variableDeclarationNode时使用了getAllPrevSiblings方法获取上面的节点。当获取到多余的节点时，由于未验证节点类型导致出现错误。
